# Generated by Django 2.2.7 on 2019-11-28 08:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfallback.fields
import tsunami.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9.-_@\\/]+')])),
                ('target_id', models.CharField(max_length=40)),
                ('data', jsonfallback.fields.FallbackJSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(default=tsunami.models._default_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'index_together': {('target_ctype', 'target_id')},
            },
        ),
        migrations.CreateModel(
            name='EventAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_id', models.CharField(max_length=40)),
                ('aggregate_ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', related_query_name='aggregate', to='tsunami.Event')),
            ],
            options={
                'ordering': ('aggregate_ctype__app_label', 'aggregate_ctype__model', 'aggregate_id'),
                'index_together': {('aggregate_ctype', 'aggregate_id')},
            },
        ),
    ]
