# Generated by Django 4.2.11 on 2024-03-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tsunami", "0002_alter_eventaggregate_id"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="event",
            new_name="tsunami_eve_target__db9ae6_idx",
            old_fields=("target_ctype", "target_id"),
        ),
        migrations.RenameIndex(
            model_name="eventaggregate",
            new_name="tsunami_eve_aggrega_c1c616_idx",
            old_fields=("aggregate_ctype", "aggregate_id"),
        ),
    ]
